import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase';
import type {
  Document,
  DocumentType,
  DocumentStatus,
  DocumentListParams,
  DocumentListResponse,
  CreateDocumentRequest,
} from '@/lib/documents/types';

// GET /api/admin/documents - List documents with filters
export async function GET(request: NextRequest) {
  try {
    const supabase = createServerClient();
    const { searchParams } = new URL(request.url);

    const params: DocumentListParams = {
      type: searchParams.get('type') as DocumentType | undefined,
      status: searchParams.get('status') as DocumentStatus | undefined,
      lead_id: searchParams.get('lead_id') || undefined,
      search: searchParams.get('search') || undefined,
      page: parseInt(searchParams.get('page') || '1'),
      limit: parseInt(searchParams.get('limit') || '20'),
      sort_by: (searchParams.get('sort_by') as DocumentListParams['sort_by']) || 'created_at',
      sort_order: (searchParams.get('sort_order') as 'asc' | 'desc') || 'desc',
    };

    // Build query
    let query = supabase
      .from('documents')
      .select(`
        *,
        lead:leads(id, name, email, company),
        signatures:document_signatures(id, signer_role, signer_name, signer_email, status, signed_at)
      `, { count: 'exact' });

    // Apply filters
    if (params.type) {
      query = query.eq('document_type', params.type);
    }

    if (params.status) {
      query = query.eq('status', params.status);
    }

    if (params.lead_id) {
      query = query.eq('lead_id', params.lead_id);
    }

    if (params.search) {
      query = query.or(`document_number.ilike.%${params.search}%,title.ilike.%${params.search}%`);
    }

    // Don't show archived by default
    if (params.status !== 'archived') {
      query = query.neq('status', 'archived');
    }

    // Apply sorting
    query = query.order(params.sort_by || 'created_at', {
      ascending: params.sort_order === 'asc',
    });

    // Apply pagination
    const page = params.page || 1;
    const limit = params.limit || 20;
    const offset = (page - 1) * limit;

    query = query.range(offset, offset + limit - 1);

    const { data: documents, error, count } = await query;

    if (error) {
      console.error('Error fetching documents:', error);
      return NextResponse.json({ error: 'Failed to fetch documents' }, { status: 500 });
    }

    const response: DocumentListResponse = {
      documents: documents as Document[],
      total: count || 0,
      page,
      limit,
      total_pages: Math.ceil((count || 0) / limit),
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('Error in GET /api/admin/documents:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/admin/documents - Create a new document
export async function POST(request: NextRequest) {
  try {
    const supabase = createServerClient();
    const body: CreateDocumentRequest = await request.json();

    // Validate required fields
    if (!body.document_type) {
      return NextResponse.json({ error: 'document_type is required' }, { status: 400 });
    }

    const validTypes: DocumentType[] = ['proposal', 'sow', 'invoice', 'change_order'];
    if (!validTypes.includes(body.document_type)) {
      return NextResponse.json({ error: 'Invalid document_type' }, { status: 400 });
    }

    // Generate default title if not provided
    let title = body.title;
    if (!title) {
      const typeLabels: Record<DocumentType, string> = {
        proposal: 'Project Proposal',
        sow: 'Statement of Work',
        invoice: 'Invoice',
        change_order: 'Change Order',
      };
      title = typeLabels[body.document_type];

      // Add client name if lead is provided
      if (body.lead_id) {
        const { data: lead } = await supabase
          .from('leads')
          .select('name, company')
          .eq('id', body.lead_id)
          .single();

        if (lead) {
          title = `${title} — ${lead.company || lead.name}`;
        }
      }
    }

    // Create document (document_number is auto-generated by trigger)
    const { data: document, error } = await supabase
      .from('documents')
      .insert({
        lead_id: body.lead_id || null,
        document_type: body.document_type,
        title,
        content_json: body.content_json || {},
        template_id: body.template_id || `${body.document_type}-v1`,
        status: 'draft',
        created_by: 'admin',
      })
      .select(`
        *,
        lead:leads(id, name, email, company)
      `)
      .single();

    if (error) {
      console.error('Error creating document:', error);
      return NextResponse.json({ error: 'Failed to create document' }, { status: 500 });
    }

    // Log activity
    await supabase.from('document_activities').insert({
      document_id: document.id,
      activity_type: 'created',
      actor: 'admin',
      description: `Document created: ${document.document_number}`,
    });

    return NextResponse.json({ document }, { status: 201 });
  } catch (error) {
    console.error('Error in POST /api/admin/documents:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
